version: 1

formatters:
  basic:
    format: '%(name)s - %(levelname)s - %(message)s'
  basic-time:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: basic
  file:
    (): app.logmaker
    formatter: basic-time
    level: ERROR

loggers:
  main-logger:
    handlers: [console,file]
root:
  handlers: [console,file]